### ISSUE TITLE
Artist profile page - no current work available

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/altonwebsites_ftloa#13]
Can you show me what it would look like if we have no current work available eg under Yaacov Agam.

Can we show the biog:
Yaacov Agam (b1929)
Yaacov Agam is an Israeli sculptor and artist best known for his op art and kinetic works.  He trained in Jerusalem before moving to Switzerland to continue his studies in 1949, where he became influenced by Max Bill. Agam moved on to Paris in 1951 where he still lives today, holding his first solo exhibition in 1953.

and then say: No works available.
Please contact us (link) to be notified when works become available.

**Comment by altonwebsites** [comment]
I've done something slightly different to what you've asked here...

I've added a button on every Artist's profile page with a line that says contact me if any new work by this artist becomes available. This covers situations in which you have nothing available by the artist (as requested), but also gives the visitor an option of registering interest in something new by the artist. Clicking the button fills in the form field the contact us page.

Does that make sense, and is that OK?

Note that
If there is no "feauture image" (as with Yaacov Agam) the biog will flow across the page.
If there is a feature image, either sold or available, the page will be 50:50 as on other Artist pages.

Close this issue if you're happy with this or Iet me know if you just want the original request

**Comment by ftloa-altonwebsites** [comment]
hi steve, yes like this idea

can you match the contact button in style / colour to the enquire button used on other pages?

Will it be easy for me to replace the button when I do have work in?

Sent from Windows Mail

From: Alton Websites
Sent: ‎Thursday‎, ‎4‎ ‎June‎ ‎2015 ‎15‎:‎37
To: altonwebsites/altonwebsites_ftloa

I've done something slightly different to what you've asked here...

I've added a button on every Artist's profile page with a line that says contact me if any new work by this artist becomes available. This covers situations in which you have nothing available by the artist (as requested), but also gives the visitor an option of registering interest in something new by the artist. Clicking the button fills in the form field the contact us page.

Does that make sense, and is that OK?

Note that
If there is no "feauture image" (as with Yaacov Agam) the biog will flow across the page.
If there is a feature image, either sold or available, the page will be 50:50 as on other Artist pages.

Close this issue if you're happy with this or Iet me know if you just want the original request

**Comment by altonwebsites** [comment]
Hi Lyndsay, 
Just checked across different browsers and between Windows and Mac, the contact me button seems identical to the enquire button. What is it that looks different to you?

Also, my intention above was that the button and text will appear on every artist's page even when there is art available. In that way visitors are able register their interest in the artist. e.g. I might like Peter Phillips, but not like anything you currently have in stock so I use that button to say contact me when you have more by Peter Phillips in. Does that make sense?

**Comment by ftloa-altonwebsites** [comment]
hi steve

just looked again and it is fine now. when I first saw it the button was light blue and the font was different.

yes makes sense to have it as you suggest as long as it is clear the Enquire button is about the work they are looking at.  Maybe it needs to say Enquire about this work    ? hard to say until I can see it!!!

Also, on sunday we sold the Peter Blake Q is for Quarters. I think it’s a good thing as will give the impression when site goes leave and we feature Peter Blake we have already sold something.  Can you switch the status on this to SOLD so I can see what that looks like?

I also sent you a long message via the hub about whether or not I should send you any more biogs or images?  I wasn’t sure at what point your time was up and don’t want to take advantage so just let me know!

many thanks Steve, it is looking fab

Lyndsay

Sent from Windows Mail

From: Alton Websites
Sent: ‎Monday‎, ‎8‎ ‎June‎ ‎2015 ‎10‎:‎17
To: altonwebsites/altonwebsites_ftloa
Cc: ftloa-altonwebsites

Hi Lyndsay, 
Just checked across different browsers and between Windows and Mac, the contact me button seems identical to the enquire button. What is it that looks different to you?

Also, my intention above was that the button and text will appear on every artist's page even when there is art available. In that way visitors are able register their interest in the artist. e.g. I might like Peter Phillips, but not like anything you currently have in stock so I use that button to say contact me when you have more by Peter Phillips in. Does that make sense?

**Comment by altonwebsites** [comment]
Hi Lyndsay, changed the Enquire to Enquire about this work. Also marked Q for Quarters as sold. Let me know if these are OK.. Replied to your longer message in the other issue.

**Comment by ftloa-altonwebsites** [comment]
thanks these are great

Sent from Windows Mail

From: Alton Websites
Sent: ‎Monday‎, ‎8‎ ‎June‎ ‎2015 ‎19‎:‎58
To: altonwebsites/altonwebsites_ftloa
Cc: ftloa-altonwebsites

Hi Lyndsay, changed the Enquire to Enquire about this work. Also marked Q for Quarters as sold. Let me know if these are OK.. Replied to your longer message in the other issue.
