### ISSUE TITLE
Contact page - add VAT

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/altonwebsites_ftloa#16]
Can you squeeze in under our names: For the Love of Art (carraige return)  VAT Registered: 201 6154 60

**Comment by altonwebsites** [comment]
Added Vat details beneath image. It looks better or worse left/center aligned depending on the image above it. Compare with a contact page that has a product enquiry.  If you're happy with it where it is, just close this issue. Other options: include in footer beside the copyright notice. i.e. C 2015 - VAT Registered: 201 6154 60, or just beneath the main text of the contact page.

**Comment by ftloa-altonwebsites** [comment]
can we try it footer as you suggest,i think that may look better?

**Comment by altonwebsites** [comment]
Moved to the footer. Will upload for you to check later
