### ISSUE TITLE
Newsletter sign-up should be on all pages

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/altonwebsites_ftloa#3]

**Comment by altonwebsites** [comment]
Added newsletter sign-up to all pages. I've also moved it from the 3rd row of the home page into the footer to make it consistent with every other page. It also makes the rows on the home page a little neater. Are you ok with this? The only page it doesn't display on is the contact page, because you're asking them to sign up within the contact form

**Comment by ftloa-altonwebsites** [comment]
great

**Comment by altonwebsites** [comment]
WIll close
