### ISSUE TITLE
contact form

### ISSUE THREAD

**Issue by ftloa-altonwebsites** [altonwebsites/altonwebsites_ftloa#32]
I sent a test contact form via the website and ticked the box to receive emails.  the email didn't come through to the inbox (now set up on my phone) - didn't come to Hotmail account either.  I also checked in subscribers and the email address I used (my Hotmail one) didn't get added to the list of subscribers.

**Comment by altonwebsites** [comment]
The contact form in the system was set up with my gmail address for testing. I've now changed this to info@loveourart.co.uk and sent a test enquiry that you should have received.

The contact form and newsletter are separate 3rd-party "plugins" so ticking the preference box in the contact form doesn't trigger the same set of process (e.g. email confirmations, unsubscribe options) as submitting an email via the newsletter sign-up box. The New Subscriber button (under Newsletter -> Subscribers) allows you to add email addresses from other sources. When you've pressed Save, click the Search button and choose "resend the confirmation". "Status" can be set as
1. confirmed - visitor has received a confirmation email and agreed to receiving newsletters
2. unconfirmed - visitor has not accepted the link in the confirmation email sent (it could be in their spam folder)
3. unsubscribed - they unsubscribed after being signed up
4. bounced - the confirmation email was sent out but was returned with an error e.g. no known email address or their email inbox was full

I've started a thread on both plugin forums to figure out whether the contact form process can trigger the newsletter sign-up process. Will make the change if I can find a solution.

Hope the above makes sense

**Comment by ftloa-altonwebsites** [comment]
hi steve

so do you mean that if someone ticks the box via the contact form we have to manually add them as it stands to receive a newsletter?

Sent from Windows Mail

From: Alton Websites
Sent: ‎Monday‎, ‎29‎ ‎June‎ ‎2015 ‎14‎:‎38
To: altonwebsites/altonwebsites_ftloa
Cc: ftloa-altonwebsites

The contact form in the system was set up with my gmail address for testing. I've now changed this to info@loveourart.co.uk and sent a test enquiry that you should have received.

The contact form and newsletter are separate 3rd-party "plugins" so ticking the preference box in the contact form doesn't trigger the same set of process (e.g. email confirmations, unsubscribe options) as submitting an email via the newsletter sign-up box. The New Subscriber button (under Newsletter -> Subscribers) allows you to add email addresses from other sources. When you've pressed Save, click the Search button and choose "resend the confirmation". "Status" can be set as
1. confirmed - visitor has received a confirmation email and agreed to receiving newsletters
2. unconfirmed - visitor has not accepted the link in the confirmation email sent (it could be in their spam folder)
3. unsubscribed - they unsubscribed after being signed up
4. bounced - the confirmation email was sent out but was returned with an error e.g. no known email address or their email inbox was full

I've started a thread on both plugin forums to figure out whether the contact form process can trigger the newsletter sign-up process. Will make the change if I can find a solution.

Hope the above makes sense

**Comment by altonwebsites** [comment]
As above, can you confirm that the emails from the contact form are received and that the addresses of subscribers appear on you mailchimp FTLOA List. Thanks

**Comment by ftloa-altonwebsites** [comment]
hi steve, just been into mailchimp and can see 2 registrations from you in there. is that right?

Sent from Windows Mail

From: Alton Websites
Sent: ‎Thursday‎, ‎2‎ ‎July‎ ‎2015 ‎14‎:‎45
To: altonwebsites/altonwebsites_ftloa
Cc: ftloa-altonwebsites

As above, can you confirm that the emails from the contact form are received and that the addresses of subscribers appear on you mailchimp FTLOA List. Thanks
