### ISSUE TITLE
shop page, sort filter

### ISSUE THREAD

**Issue by ftloa-altonwebsites** [altonwebsites/altonwebsites_ftloa#35]
just a small cosmetic thing but on the shop page there appears to be a box behind the drop down sort box to the righthand side?

**Comment by altonwebsites** [comment]
That's an interesting one. It's a well known bug on a specific browser that I thought I'd dealt with.  I need to know what browser you're using. 

Are you seeing this on Windows or Mac or iPad, and is the browser Internet Explorer, Chrome, Firefox, Opera?

**Comment by ftloa-altonwebsites** [comment]
its on a laptop, internet explorer.

Sent from Windows Mail

From: Alton Websites
Sent: ‎Monday‎, ‎29‎ ‎June‎ ‎2015 ‎15‎:‎34
To: altonwebsites/altonwebsites_ftloa
Cc: ftloa-altonwebsites

That's an interesting one. It's a well known bug on a specific browser that I thought I'd dealt with. I need to know what browser you're using. 

Are you seeing this on Windows or Mac or iPad, and is the browser Internet Explorer, Chrome, Firefox, Opera?

**Comment by altonwebsites** [comment]
I've removed the graphical dropdown that was overlaid on top of the Internet Explorer dropdown.
