### ISSUE TITLE
Multiline titles in shop break result in inconsistent box height

### ISSUE THREAD

**Issue by altonwebsites** [altonwebsites/altonwebsites_ftloa#37]

**Comment by altonwebsites** [comment]
Tried creating more space and making the font size smaller but decided that the odd slightly larger box e.g. Head (from Daybook by Robert Creeley)   in the Shop page, is relatively neat. Are you ok with this? Another option would be to automatically truncate the title?

**Comment by ftloa-altonwebsites** [comment]
I think it’s fine as is thanks steve

Sent from Windows Mail

From: Alton Websites
Sent: ‎Friday‎, ‎3‎ ‎July‎ ‎2015 ‎16‎:‎04
To: altonwebsites/altonwebsites_ftloa

Tried creating more space and making the font size smaller but decided that the odd slightly larger box e.g. Head (from Daybook by Robert Creeley) in the Shop page, is relatively neat. Are you ok with this? Another option would be to automatically truncate the title?
